# Generated by Django 4.2.10 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('emai', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('tandc', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
