# Generated by Django 4.2.10 on 2024-02-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='emai',
            new_name='email',
        ),
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
