# Generated by Django 4.2.10 on 2024-02-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0002_alter_signup_options_rename_emai_signup_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tandc', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
