# Generated by Django 4.2.10 on 2024-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('product_dict', models.CharField(max_length=120)),
                ('product_price', models.CharField(max_length=120)),
                ('product_img', models.FileField(max_length=120, upload_to='')),
            ],
        ),
    ]
