# Generated by Django 4.2.11 on 2024-04-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='image',
        ),
    ]
